In [4]:
import numpy as np

print(np.__version__)
a = np.array([1, 2, 3, 4])
b = np.array([2, 4, 6, 8])
#Arithmetic Operations
print(a+b)
print(a-b)
print(a*b)
print(a/b)

2.5.0
[ 3  6  9 12]
[-1 -2 -3 -4]
[ 2  8 18 32]
[0.5 0.5 0.5 0.5]


In [ ]:
# n-Dimensional Array & indxing slicing
arr = np.array([[1, 2],
               [3, 4]])
print(arr[1:])
print(arr[1][1])
#3-Dimensional Array
arr3 = np.array([
    [[1, 2],
     [3, 4]],

    [[5, 6],
     [7, 8]]
])

print(arr3)



In [34]:
#Array Attributes
print(arr.shape,
arr.ndim,
arr.size,
arr.dtype)

(2, 2) 2 4 int64


In [ ]:
#Built-in Function 
print(np.zeros(5))
print(np.ones(5))
print(np.zeros((2,10,2)))
print(np.full((2,3),45))
print(np.eye(3))
print(np.arange(0,8,2))
print(np.linspace(0,100,6))

In [36]:
#Statistical operations
print(np.mean(arr),
np.median(arr),
np.std(arr),
np.var(arr),
np.min(arr),
np.max(arr),
np.sum(arr))

2.5 2.5 1.118033988749895 1.25 1 4 10
